// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const deleteBundleEntries = `-- name: DeleteBundleEntries :exec
DELETE FROM bundle_entries WHERE bundle_id = $1
`

func (q *Queries) DeleteBundleEntries(ctx context.Context, bundleID int64) error {
	_, err := q.db.Exec(ctx, deleteBundleEntries, bundleID)
	return err
}

const insertBundleEntries = `-- name: InsertBundleEntries :exec
INSERT INTO bundle_entries (bundle_id, frame_offset, url)
SELECT $1, positions.frame_position, urls.url
FROM unnest($2::bigint[]) WITH ORDINALITY AS positions(frame_position, n)
JOIN unnest($3::text[]) WITH ORDINALITY AS urls(url, n) USING (n)
`

type InsertBundleEntriesParams struct {
	BundleID     int64    `json:"bundle_id"`
	FrameOffsets []int64  `json:"frame_offsets"`
	Urls         []string `json:"urls"`
}

func (q *Queries) InsertBundleEntries(ctx context.Context, arg InsertBundleEntriesParams) error {
	_, err := q.db.Exec(ctx, insertBundleEntries, arg.BundleID, arg.FrameOffsets, arg.Urls)
	return err
}

const upsertBundle = `-- name: UpsertBundle :one
INSERT INTO bundles (object_key) VALUES ($1)
ON CONFLICT (object_key) DO UPDATE SET object_key = EXCLUDED.object_key
RETURNING id
`

func (q *Queries) UpsertBundle(ctx context.Context, objectKey string) (int64, error) {
	row := q.db.QueryRow(ctx, upsertBundle, objectKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}
